### ISSUE TITLE
just running your example and getting this error while opening camera

### ISSUE THREAD

**Issue by tejEtrix** [alexdar94/ARUserManual#1]
09-19 17:12:03.675 32492-32492/com.tp034766.arusermanual E/SceneLoader: There was a problem opening file/asset 'models/ArrowSign.obj'
    java.lang.RuntimeException: There was a problem opening file/asset 'models/ArrowSign.obj'
        at com.tp034766.arusermanual.model3D.services.wavefront.WavefrontLoader2$1.getInputStream(WavefrontLoader2.java:44)
        at com.tp034766.arusermanual.model3D.services.wavefront.WavefrontLoader2$1.build(WavefrontLoader2.java:62)
        at com.tp034766.arusermanual.model3D.controller.LoaderTask.doInBackground(LoaderTask.java:86)
        at com.tp034766.arusermanual.model3D.controller.LoaderTask.doInBackground(LoaderTask.java:18)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by tejEtrix** [comment]
please solve the above issue.
